apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  # Nginx bu ismi kullanıyor. Proxypass yaparken
  # Bu isim o yüzden çok önemli, değiştirme
  labels:
    app: backend-restapp
    tier: backend
spec:
  type: ClusterIP #Default values
  selector:
    app: backend-restapp
  ports:
    - name: http
      targetPort: 8080 #Container Port
      port: 8080
      #nodePort değeri ClusterIP ile olmaz YASSAK
