apiVersion: v1
kind: Pod # OR ReplicaSet | Deployment # falan filan
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers: #List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
