apiVersion: v1
kind: Service
metadata:
  name: myapp3-nodeport-service
spec:
  type: NodePort
  selector:
    app: myapp3
  ports:
    - name: http
      nodePort: 31111
      port: 80
      targetPort: 80